// public/EaAgri_Durian_3D_Dev_Kit_v2/EaAgri_Durian_3D_Dev_Kit_v2/examples/EaAgriDurian.tsx
'use client';
import {useEffect,useRef} from 'react';
import {createEaAgriScene} from '../src/viewer.mjs';
import type {EaAgriData,EaAgriViewer,Selection} from '../src/viewer.mjs';
import '../src/viewer.css';

export default function EaAgriDurian({
  assetBaseUrl='/eaagri-3d/assets/',data={source:'none'},onSelect,quality='auto',
}: {
  assetBaseUrl?:string; data?:EaAgriData; onSelect?:(e:Selection)=>void;
  quality?:'auto'|'high'|'mobile';
}){
  const host=useRef<HTMLDivElement>(null),viewer=useRef<EaAgriViewer|null>(null);
  const callback=useRef(onSelect),currentData=useRef(data);
  callback.current=onSelect;currentData.current=data;
  useEffect(()=>{
    if(!host.current)return;
    const scene=createEaAgriScene(host.current,{
      assetBaseUrl,posterUrl:assetBaseUrl+'poster.png',quality,
      data:currentData.current,onSelect:event=>callback.current?.(event),
    });
    viewer.current=scene;
    return()=>{scene.destroy();if(viewer.current===scene)viewer.current=null;};
  },[assetBaseUrl,quality]);
  useEffect(()=>{viewer.current?.setData(data);},[data]);
  return <div ref={host} style={{width:'100%',height:'clamp(400px,44vw,680px)'}} />;
}

// public/EaAgri_Durian_3D_Dev_Kit_v2/EaAgri_Durian_3D_Dev_Kit_v2/examples/EaAgriDurian.vue
<script setup>
import {onMounted,onBeforeUnmount,ref,watch} from 'vue';
import {createEaAgriScene} from '../src/viewer.mjs';
import '../src/viewer.css';
const props=defineProps({assetBaseUrl:{type:String,default:'/eaagri-3d/assets/'},quality:{type:String,default:'auto'},data:{type:Object,default:()=>({source:'none'})}});
const emit=defineEmits(['select']);const host=ref(null);let scene;
function mount(){scene?.destroy();scene=createEaAgriScene(host.value,{assetBaseUrl:props.assetBaseUrl,posterUrl:props.assetBaseUrl+'poster.png',quality:props.quality,data:props.data,onSelect:event=>emit('select',event)});}
onMounted(mount);
watch(()=>[props.assetBaseUrl,props.quality],()=>{if(host.value)mount();});
watch(()=>props.data,value=>scene?.setData(value),{deep:true});
onBeforeUnmount(()=>scene?.destroy());
</script>
<template><div ref="host" style="width:100%;height:clamp(400px,44vw,680px)" /></template>
