// public/EaAgri_Durian_3D_Dev_Kit_v2/EaAgri_Durian_3D_Dev_Kit_v2/examples/EaAgriDurian.vue
<script setup>
import {onMounted,onBeforeUnmount,ref,watch} from 'vue';
import {createEaAgriScene} from '../src/viewer.mjs';
import '../src/viewer.css';
const props=defineProps({assetBaseUrl:{type:String,default:'/eaagri-3d/assets/'},quality:{type:String,default:'auto'},data:{type:Object,default:()=>({source:'none'})}});
const emit=defineEmits(['select']);const host=ref(null);let scene;
function mount(){scene?.destroy();scene=createEaAgriScene(host.value,{assetBaseUrl:props.assetBaseUrl,posterUrl:props.assetBaseUrl+'poster.png',quality:props.quality,data:props.data,onSelect:event=>emit('select',event)});}
onMounted(mount);
watch(()=>[props.assetBaseUrl,props.quality],()=>{if(host.value)mount();});
watch(()=>props.data,value=>scene?.setData(value),{deep:true});
onBeforeUnmount(()=>scene?.destroy());
</script>
<template><div ref="host" style="width:100%;height:clamp(400px,44vw,680px)" /></template>

// src/components/eaagri-3d/EaAgriDurian.tsx
'use client';
import { useEffect, useRef } from 'react';
import { createEaAgriScene } from './viewer.mjs';
import type { EaAgriData, EaAgriViewer, Selection } from './viewer.d.mts';
import './viewer.css';

export interface EaAgriDurianProps {
  assetBaseUrl?: string;
  posterUrl?: string;
  data?: EaAgriData;
  onSelect?: (e: Selection) => void;
  quality?: 'auto' | 'high' | 'mobile';
  showCards?: boolean;
  showHotspots?: boolean;
  showFarmer?: boolean;
  autoRotate?: boolean;
  className?: string;
  style?: React.CSSProperties;
}

export default function EaAgriDurian({
  assetBaseUrl = '/eaagri-3d/assets/',
  posterUrl = '/eaagri-3d/assets/poster.png',
  data = {
    source: 'demo',
    treeName: 'Sầu riêng Ri6 EaAgri',
    growthStage: 'Giai đoạn nuôi trái (90 ngày)',
    moistureTop: 68,
    moistureDeep: 72,
    temperature: 28,
    rainMm: 12,
    pumpOn: true,
    diseaseNote: 'Lá xanh dày, phát triển tối ưu',
  },
  onSelect,
  quality = 'auto',
  showCards = false,
  showHotspots = true,
  showFarmer = true,
  autoRotate = false,
  className = '',
  style,
}: EaAgriDurianProps) {
  const host = useRef<HTMLDivElement>(null);
  const viewer = useRef<EaAgriViewer | null>(null);
  const callback = useRef(onSelect);
  const currentData = useRef(data);
  callback.current = onSelect;
  currentData.current = data;

  useEffect(() => {
    if (!host.current) return;
    const scene = createEaAgriScene(host.current, {
      assetBaseUrl,
      posterUrl,
      quality,
      showCards,
      showHotspots,
      showFarmer,
      autoRotate,
      data: currentData.current,
      onSelect: (event) => callback.current?.(event),
    });
    viewer.current = scene;

    return () => {
      scene.destroy();
      if (viewer.current === scene) viewer.current = null;
    };
  }, [assetBaseUrl, posterUrl, quality, showCards, showHotspots, showFarmer, autoRotate]);

  useEffect(() => {
    viewer.current?.setData(data);
  }, [data]);

  return (
    <div
      ref={host}
      className={`eaagri-durian-3d-container ${className}`}
      style={{
        width: '100%',
        height: '100%',
        minHeight: '480px',
        position: 'relative',
        ...style,
      }}
    />
  );
}
